### ISSUE TITLE
a shell command instead of python command in terminal

### ISSUE THREAD

**Issue by getsadzeg** [ch3k1/squidmagic#1]
It would be better if we could run squidmagic with shell comand like 'squidmagic -start' or something like that instead of 'python squidmagic.py'

**Comment by AWS-alchemy** [comment]
Hi, 
yes, it  would be better to create squidmagic service, but at this moment IM working to write squdmagic web based gui, w8 next release

thank

**Comment by getsadzeg** [comment]
Okay.
